version: "3.0"
services:
  db:
    image: mysql
    container_name: "security_db"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_DABABASE=testdb
    
    